name: experiment

# Run this action on code push or branch/tag creation
on: [create, push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: bahmutov/npm-install@v1
      with:
        working-directory: github-actions

    # Use an action (`my-action`) in your repository
    - name: Generate github_data.json
      id: json
      uses: ./github-actions/action.yml
