name: experiment

# Run this action on code push or branch/tag creation
on: [create, push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: bahmutov/npm-install@v1
      with:
        working-directory: github-actions

    # Use an action (`my-action`) in your repository
    - name: Generate github_data.json
      id: json
      uses: ./github-actions

    - uses: stefanzweifel/git-auto-commit-action@v3.0.0
      with:
        # Optional glob pattern of files which should be added to the commit
        file_pattern: github-actions/github_data.json

        commit_message: Update contributor and language data

        # Optional commit user and author settings
        commit_user_name: GitHub Actions Bot
        commit_user_email: github-actions-bot@hackforla.org

